FROM python:3.10

WORKDIR /Backend

COPY Backend/requirements/requirements.txt /requirements/requirements.txt

# Install dependencies
RUN apt-get update && \
    apt-get install -y libgl1-mesa-glx default-libmysqlclient-dev

# Upgrade pip
RUN pip install --upgrade pip

# Install Python dependencies
RUN pip install --no-cache-dir -r /requirements/requirements.txt
RUN pip freeze > /requirements/requirements.txt

# Copy the application code
COPY Backend .

# Set environment variables
ENV FLASK_APP=run.py
ENV FLASK_DATABASE_MIGRATE_DIR=src/migrations

# Run the application
CMD python -u run.py
