version: '3.8'

services:
  backend:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: Dockerfile-Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/Backend
    restart: always
  db:
    image: mariadb:10.8
    container_name: Database
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: back
      MYSQL_ROOT_PASSWORD: password

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "1333:8080"
